server:
  ip: 0.0.0.0
  port: 6666
log:
  level: "info"
  logPath: "runtime/logs/app.log"
embedding: # Embedding 模型，将问题文本转化为数字向量
  api_key: "sk-ws-H.EHMRRDL.G7qC.MEYCIQDxxspnatsngz5745n4-PHFyd-RNN9qkEtP0qqgyN7q-AIhALORmoklQ_D169zkMFO55Ri-yiXor2OmtC616Cnpp6Ar"
  base_url: "https://ws-7wl00bp88ie0ya61.cn-beijing.maas.aliyuncs.com/compatible-mode/v1/embeddings" 
  model: "qwen3.7-text-embedding"
  vector_dimensions: 1024
  recall_score: 0.85
  topK: 10
rerank: 
  api_key: "sk-ws-H.EXLXHEY.e3aR.MEUCIQDc_2mj06qTCurGhKMgWzprHlgcsO1pLo1T4gsYy-MrxwIgIyJEFtKb1hdUV3qmsgxbFbcmyUAOlqSznpL8gLV-zmg"
  base_url: "https://ws-7wl00bp88ie0ya61.cn-beijing.maas.aliyuncs.com/compatible-api/v1/reranks" 
  model: "qwen3-rerank"
  instruct: "Retrieve semantically similar text"
  rerank_score: 0.85
cache:
  ip: 192.168.184.138
  port: 2000
